version: '3'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: host.docker.internal
      PMA_USER: sammy
      PMA_PASSWORD: password
    ports:
      - "8080:80"
